// Generated by CoffeeScript 1.10.0
var ContentEditable, EditableField, NewRow, ObjectEditor, React, asString, nonNullKeys, parseValue;

React = require('react');

ContentEditable = require('react-contenteditable');

nonNullKeys = function(o) {
  var k, ks, v;
  ks = [];
  for (k in o) {
    v = o[k];
    if (v != null) {
      ks.push(k);
    }
  }
  return ks;
};

parseValue = function(s) {
  if (s.match(/^\d+$/)) {
    return Number(s);
  } else if (s === 'true' || s === 'false') {
    return s === 'true';
  } else if (s === '{}') {
    return {};
  } else if (s === '[]') {
    return [];
  } else {
    return s;
  }
};

EditableField = React.createClass({displayName: "EditableField",
  getInitialState: function() {
    return {
      value: this.props.value
    };
  },
  componentWillReceiveProps: function(new_props) {
    var new_value;
    if (new_value = new_props.value) {
      return this.setState({
        value: new_value
      });
    }
  },
  empty: function() {
    var ref;
    return !((ref = this.state.value) != null ? ref.length : void 0);
  },
  onChange: function(e) {
    var edited, value;
    value = e.target.value;
    value = parseValue(value);
    edited = value !== this.props.value;
    return this.setState({
      value: value,
      edited: edited
    });
  },
  onKeyDown: function(e) {
    if (e.keyCode === 13) {
      e.preventDefault();
      return this.save();
    }
  },
  save: function() {
    console.log('[EditableField save]', this.state);
    this.props.onSave(this.state.value);
    this.setState({
      edited: false
    });
    if (this.props.clearOnSave) {
      return this.setState({
        value: ''
      });
    }
  },
  focus: function() {
    return this.refs.input.htmlEl.focus();
  },
  render: function() {
    var className;
    className = (this.props.className || '') + ' editable-field' + (this.state.edited ? ' edited' : '');
    className += ' value value-' + typeof this.state.value;
    if (this.props.value == null) {
      className += ' new';
    }
    return React.createElement("div", {
      "className": className
    }, React.createElement(ContentEditable, {
      "ref": 'input',
      "html": asString(this.state.value),
      "onChange": this.onChange,
      "disabled": this.props.disabled,
      "onKeyDown": this.onKeyDown,
      "placeholder": this.props.placeholder
    }), (this.empty() ? React.createElement("span", {
      "className": 'placeholder'
    }, this.props.placeholder) : void 0));
  }
});

asString = function(value) {
  if (typeof value === 'object') {
    return JSON.stringify(value);
  } else {
    return value;
  }
};

NewRow = React.createClass({
  displayName: 'NewRow',
  getInitialState: function() {
    return {
      key: this.props.static_key != null ? this.props.static_key : '',
      value: '',
      errors: {}
    };
  },
  componentDidMount: function() {
    if (this.props.static_key != null) {
      return this.refs.value.htmlEl.focus();
    } else {
      return this.refs.key.htmlEl.focus();
    }
  },
  onChange: function(key) {
    return (function(_this) {
      return function(e) {
        var change, value;
        console.log('[NewRow onChange]', key, e.target.value);
        value = e.target.value;
        change = {};
        change[key] = value;
        return _this.setState(change);
      };
    })(this);
  },
  errors: function() {
    return {
      key: !this.state.key.length && (this.props.static_key == null) ? true : void 0,
      value: !this.state.value.length ? true : void 0
    };
  },
  trySave: function() {
    var errors;
    console.log('[NewRow trySave]');
    if (nonNullKeys(errors = this.errors()).length > 0) {
      console.log('errors', errors);
      return this.setState({
        errors: errors
      });
    } else {
      return this.save();
    }
  },
  save: function() {
    var key, ref, row, value;
    console.log('[NewRow save]');
    ref = this.state, key = ref.key, value = ref.value;
    value = parseValue(value);
    row = {};
    row[key] = value;
    this.props.onSave(row);
    this.setState(this.getInitialState());
    return this.refs.key.htmlEl.focus();
  },
  onKeyDown: function(key) {
    return (function(_this) {
      return function(e) {
        if (e.keyCode === 13) {
          e.preventDefault();
          if (key === 'key') {
            if (_this.state.key.length > 0) {
              _this.refs.value.htmlEl.focus();
            }
          } else if (key === 'value') {
            _this.trySave();
          }
        }
        if (e.keyCode === 8) {
          if (key === 'key') {
            if (_this.state.key.length === 0) {
              return _this.props.onCancel();
            }
          } else if (key === 'value') {
            if (_this.state.value.length === 0) {
              if (_this.props.static_key != null) {
                return _this.props.onCancel();
              } else {
                return _this.refs.key.htmlEl.focus();
              }
            }
          }
        }
      };
    })(this);
  },
  onBlur: function() {
    console.log(document.activeElement);
    console.log('key', this.refs.key.htmlEl.focus);
    return console.log('value', this.refs.value.htmlEl.focus);
  },
  render: function() {
    return React.createElement("div", {
      "className": 'new-row'
    }, React.createElement(ContentEditable, {
      "ref": 'key',
      "html": this.state.key,
      "onChange": this.onChange('key'),
      "onKeyDown": this.onKeyDown('key'),
      "placeholder": 'new key',
      "disabled": (this.props.static_key != null),
      "onBlur": this.onBlur
    }), React.createElement(ContentEditable, {
      "ref": 'value',
      "html": asString(this.state.value),
      "onChange": this.onChange('value'),
      "onKeyDown": this.onKeyDown('value'),
      "placeholder": 'new value'
    }));
  }
});

ObjectEditor = React.createClass({
  displayName: 'ObjectEditor',
  getInitialState: function() {
    return {
      object: this.props.object,
      adding: false
    };
  },
  componentWillReceiveProps: function(new_props) {
    var new_object;
    if (new_object = new_props.object) {
      return this.setState({
        object: new_object
      });
    }
  },
  saveRow: function(key) {
    return (function(_this) {
      return function(value) {
        var object;
        object = _this.state.object;
        object[key] = value;
        _this.setState({
          object: object
        });
        return _this.props.onSave(object);
      };
    })(this);
  },
  saveEntire: function(object) {
    this.setState({
      object: object
    });
    return this.props.onSave(object);
  },
  updateKey: function(old_key) {
    return (function(_this) {
      return function(new_key) {
        var object, value;
        object = _this.state.object;
        value = object[old_key];
        delete object[old_key];
        object[new_key] = value;
        _this.setState({
          object: object
        });
        return _this.props.onSave(object);
      };
    })(this);
  },
  addRow: function(row) {
    var object;
    console.log("[addRow] " + (JSON.stringify(row)));
    object = this.state.object;
    Object.assign(object, row);
    this.setState({
      object: object,
      adding: false
    }, this.focusAdder);
    return this.props.onSave(object);
  },
  addValue: function(row) {
    var object, value;
    value = row[Object.keys(row)[0]];
    console.log("[addValue] " + (JSON.stringify(value)));
    object = this.state.object;
    object.push(value);
    this.setState({
      object: object,
      adding: false
    }, this.focusAdder);
    return this.props.onSave(object);
  },
  deleteRow: function(key) {
    return (function(_this) {
      return function() {
        var object;
        console.log("[deleteRow] " + (JSON.stringify(key)));
        object = _this.state.object;
        if (Array.isArray(object)) {
          object.splice(key, 1);
        } else {
          delete object[key];
        }
        _this.setState({
          object: object
        });
        return _this.props.onSave(object);
      };
    })(this);
  },
  focusAdder: function() {
    return this.refs.adder.focus();
  },
  showAddRow: function() {
    return this.setState({
      adding: true
    });
  },
  hideAddRow: function() {
    return this.setState({
      adding: false
    }, this.focusAdder);
  },
  render: function() {
    var editor_class_name;
    if (typeof this.state.object === 'object') {
      if (Array.isArray(this.state.object)) {
        editor_class_name = 'array-editor';
      } else {
        editor_class_name = 'object-editor';
      }
      return React.createElement("div", {
        "className": editor_class_name
      }, Object.keys(this.state.object).map((function(_this) {
        return function(key) {
          var key_class_name, value;
          value = _this.state.object[key];
          return React.createElement("div", {
            "className": 'row',
            "key": key
          }, React.createElement("span", {
            "className": 'key'
          }, React.createElement(EditableField, {
            "onSave": _this.updateKey(key),
            "value": key,
            "disabled": Array.isArray(_this.state.object)
          }), (typeof value === 'object' ? (Array.isArray(value) ? key_class_name = 'key-extra-array' : key_class_name = 'key-extra-object', React.createElement("span", {
            "className": key_class_name
          }, (Array.isArray(value) ? "[ " + value.length + " ]" : "{ " + Object.keys(value).length + " }"))) : void 0)), React.createElement(ObjectEditor, {
            "object": value,
            "onSave": _this.saveRow(key)
          }), React.createElement("div", {
            "className": 'actions'
          }, React.createElement("a", {
            "onClick": _this.deleteRow(key),
            "className": 'delete button'
          }, React.createElement("i", {
            "className": 'fa fa-close'
          }))));
        };
      })(this)), (typeof this.state.object === 'object' ? this.state.adding ? Array.isArray(this.state.object) ? React.createElement(NewRow, {
        "onSave": this.addValue,
        "static_key": this.state.object.length,
        "onCancel": this.hideAddRow
      }) : React.createElement(NewRow, {
        "onSave": this.addRow,
        "onCancel": this.hideAddRow
      }) : React.createElement("button", {
        "ref": 'adder',
        "className": 'adder',
        "onClick": this.showAddRow
      }, "+") : void 0));
    } else {
      return React.createElement(EditableField, {
        "className": 'value-editor',
        "value": this.state.object,
        "onSave": this.saveEntire
      });
    }
  }
});

module.exports = {
  EditableField: EditableField,
  ObjectEditor: ObjectEditor
};
